# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - vote/*

resources:
- repo: self

pool:
  name: NishantAgent
  demands:
   - agent.name -equals myagent1

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build       
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'devops-decker-con'
        repository: 'nishant4028/votingappvote'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'

- stage: Push
  displayName: push image
  jobs:
  - job: push
    displayName: push      
    steps:
    - task: Docker@2
      displayName: Push image to docker hub
      inputs:
        containerRegistry: 'devops-decker-con'
        repository: 'nishant4028/votingappvote'
        command: 'push'
        tags: '$(tag)'

- stage: k8s_deployment_Updating
  displayName: k8s deployment Updating
  jobs:
  - job: k8s_deployment_Updating
    displayName: k8s deployment Updating   
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'azuredev-azure-con'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: 'script/k8sManifestupdate.sh'
          arguments: 'vote votingappvote $(tag) $(GITHUB_PAT)'