---
- name: Configure VM and install required packages
  hosts: all
  become: yes

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install OpenJDK 17 JRE headless
      apt:
        name: openjdk-17-jre-headless
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Give permission to all users to run Docker commands
      command: chmod 666 /var/run/docker.sock

    - name: Pull SonarQube Docker image
      docker_image:
        name: mc1arke/sonarqube-with-community-branch-plugin
        source: pull

    - name: Run SonarQube container
      docker_container:
        name: sonar
        image: mc1arke/sonarqube-with-community-branch-plugin
        state: started
        ports:
          - "9000:9000"

    - name: Install Trivy
      snap:
        name: trivy
        state: present

    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install pip for Python
      apt:
        name: python3-pip
        state: present

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install .NET SDK
      apt:
        name: dotnet-sdk-8.0
        state: present

    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes
